CSVParseError: Error failed to create DataFrame with different column tables.
Try to set `multiple_tables=True`or set `names` option for `pandas_options`. 
, caused by ParserError('Error tokenizing data. C error: Expected 4 fields in line 4, saw 15\n')
ParserError                               Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/tabula/io.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, user_agent, use_raw_url, pages, guess, area, relative_area, lattice, stream, password, silent, columns, relative_columns, format, batch, output_path, options)
    449         try:
--> 450             return [pd.read_csv(io.BytesIO(output), **pandas_options)]
    451         except pd.errors.ParserError as e:

~/.local/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    310                 )
--> 311             return func(*args, **kwargs)
    312 

~/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    585 
--> 586     return _read(filepath_or_buffer, kwds)
    587 

~/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py in _read(filepath_or_buffer, kwds)
    487     with parser:
--> 488         return parser.read(nrows)
    489 

~/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py in read(self, nrows)
   1046         nrows = validate_integer("nrows", nrows)
-> 1047         index, columns, col_dict = self._engine.read(nrows)
   1048 

~/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py in read(self, nrows)
    223             if self.low_memory:
--> 224                 chunks = self._reader.read_low_memory(nrows)
    225                 # destructive to chunks

~/.local/lib/python3.7/site-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read_low_memory()

~/.local/lib/python3.7/site-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

~/.local/lib/python3.7/site-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

~/.local/lib/python3.7/site-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 4 fields in line 4, saw 15


During handling of the above exception, another exception occurred:

CSVParseError                             Traceback (most recent call last)
/tmp/ipykernel_114/1215835711.py in <module>
      1 if __name__ == "__main__":
----> 2     excecute_process()

/tmp/ipykernel_114/4117894532.py in excecute_process()
     35 
     36         # Parsear (horizontal)
---> 37         df = pfh.read_file(str(local_pdf_path))
     38         print("Aqui vienen los types:-----------------")
     39         print("\n--- TIPOS DEL DATAFRAME ---")

~/competitor_data/purina_file_horizontal.py in read_file(path)
     58     )
     59     if not dfs:
---> 60         raise RuntimeError("Tabula no extrajo ninguna tabla del PDF.")
     61 
     62     df = dfs[0]

~/.local/lib/python3.7/site-packages/tabula/io.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, user_agent, use_raw_url, pages, guess, area, relative_area, lattice, stream, password, silent, columns, relative_columns, format, batch, output_path, options)
    456             )
    457 
--> 458             raise CSVParseError(message, e)
    459 
    460 

CSVParseError: Error failed to create DataFrame with different column tables.
Try to set `multiple_tables=True`or set `names` option for `pandas_options`. 
, caused by ParserError('Error tokenizing data. C error: Expected 4 fields in line 4, saw 15\n
